"""
harness/compare.py
==================

Read all schema-conformant CSVs in `--predictions-dir` and produce the
per-mechanism summary table, the blocker breakdown, and (if the sweep
CSV is present) the per-spec sweep table referenced in chapter 5.

This script imports nothing from the per-mechanism simulators. The
schema in `cross_mechanism/schema.py` is the only contract.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from cross_mechanism.schema import (
    CROSS_MECHANISM_COLUMNS, KNOWN_BLOCKERS, LOWER_IS_BETTER, validate_schema,
)


def load_predictions_dir(pred_dir: Path) -> pd.DataFrame:
    """Concatenate every *_predictions.csv and *_actuals.csv into one frame."""
    frames = []
    for path in sorted(pred_dir.glob("*_predictions.csv")):
        df = pd.read_csv(path)
        validate_schema(df)
        frames.append(df)
    for path in sorted(pred_dir.glob("*_actuals.csv")):
        df = pd.read_csv(path)
        validate_schema(df)
        frames.append(df)
    if not frames:
        raise SystemExit(f"No *_predictions.csv or *_actuals.csv in {pred_dir}")
    return pd.concat(frames, ignore_index=True)


def per_mechanism_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Summarize the pool, the predictions, and the score distribution."""
    rows = []
    for mech, sub in df.groupby("mechanism"):
        pred_winners = sub[sub["predicted_award"] > 0]
        pred_losers = sub[sub["predicted_award"] == 0]
        actual_winners = sub[sub["actual_award"].fillna(0) > 0]
        score_dir = "lower-is-better" if mech in LOWER_IS_BETTER else "higher-is-better"
        rows.append({
            "mechanism":                 mech,
            "pool_size":                 len(sub),
            "predicted_awards":          len(pred_winners),
            "actual_awards":             len(actual_winners),
            "predicted_acceptance_rate": round(len(pred_winners) / max(len(sub), 1), 3),
            "actual_acceptance_rate":    round(len(actual_winners) / max(len(sub), 1), 3),
            "median_score_winners":      round(pred_winners["score_or_priority"].median(), 1) if len(pred_winners) else float("nan"),
            "median_score_losers":       round(pred_losers["score_or_priority"].median(), 1) if len(pred_losers) else float("nan"),
            "min_score_winner":          round(pred_winners["score_or_priority"].min(), 1) if len(pred_winners) else float("nan"),
            "max_score_loser":           round(pred_losers["score_or_priority"].max(), 1) if len(pred_losers) else float("nan"),
            "score_direction":           score_dir,
            "total_requested_$M":        round(sub["request_amount"].sum() / 1e6, 1),
            "total_predicted_award_$M":  round(sub["predicted_award"].sum() / 1e6, 1),
            "total_actual_award_$M":     round(sub["actual_award"].fillna(0).sum() / 1e6, 1),
        })
    return pd.DataFrame(rows)


def blocker_breakdown(df: pd.DataFrame) -> pd.DataFrame:
    """For losers only: how many were blocked by each reason, per mechanism."""
    losers = df[df["predicted_award"] == 0].copy()
    losers["predicted_blocked_by"] = losers["predicted_blocked_by"].fillna("").replace("", "outcompeted")
    pivot = losers.groupby(["mechanism", "predicted_blocked_by"]).size().unstack(fill_value=0)
    return pivot


def write_report(out_dir: Path, summary: pd.DataFrame, blockers: pd.DataFrame,
                 sweep: pd.DataFrame | None) -> None:
    """Write a single Markdown report consolidating all of the above."""
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / "report.md"
    with open(md_path, "w") as f:
        f.write("# Cross-mechanism comparison report\n\n")
        f.write("Auto-generated by `harness/compare.py`. Reflects the CSVs in "
                "`--predictions-dir` at the time of the run.\n\n")
        f.write("## Per-mechanism summary\n\n")
        f.write(summary.to_markdown(index=False))
        f.write("\n\n## Blocker breakdown (losers only)\n\n")
        f.write(blockers.to_markdown())
        if sweep is not None:
            f.write("\n\n## Synthetic-project sweep\n\n")
            f.write(sweep.to_markdown(index=False))
        f.write("\n")
    print(f"Wrote {md_path}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--predictions-dir", type=Path, default=Path("out"),
                    help="Directory containing *_predictions.csv and *_actuals.csv.")
    ap.add_argument("--sweep-dir", type=Path, default=Path("out"),
                    help="Directory containing synthetic_sweep_by_spec.csv.")
    ap.add_argument("--out-dir", type=Path, default=Path("out"),
                    help="Output directory for summary CSVs and report.md.")
    args = ap.parse_args()

    df = load_predictions_dir(args.predictions_dir)
    summary = per_mechanism_summary(df)
    blockers = blocker_breakdown(df)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    summary.to_csv(args.out_dir / "summary_table.csv", index=False)
    blockers.to_csv(args.out_dir / "blocker_breakdown.csv")
    print("Per-mechanism summary:")
    print(summary.to_string(index=False))
    print()
    print("Blocker breakdown:")
    print(blockers.to_string())

    sweep_path = args.sweep_dir / "synthetic_sweep_by_spec.csv"
    sweep_df = pd.read_csv(sweep_path) if sweep_path.exists() else None
    write_report(args.out_dir, summary, blockers, sweep_df)


if __name__ == "__main__":
    main()
